<?php

return [

	'date' => [
		'month-name' => 'F Y',
		'day-name' => 'l j.',
		'day' => 'j.',
		'date' => 'j. F Y',
		'date-short' => 'j. F',
		'time' => 'H:i',
	],

	'link' => [
		'need_password' => 'Need a password?',
	],

	'message' => [
		'email_sent' => 'The e-mail is sent! We answer as soon as we can :)',
		'reset_sent' => 'E-mail sent! You should shortly receive an e-mail with a link allowing you to login and choose a password.',
		'cookies' => 'Cookies are used to analyze traffic, and when a member logs in.',
	],
	
	'error' => [
		'invalid_token' => 'Invalid reset token.',
		'invalid_login' => 'Invalid login.',
		'not_a_member' => 'Not registered to a member.',
		'email_fail' => 'Failed to send email. Please check your input.',
		
		'not_empty' => 'Cannot be empty',
		'email' => 'Invalid email address',
		'email_domain' => 'Invalid email domain',
	],
];
