<?php

return [

	'date' => [
		'month-name' => 'F Y',
		'day-name' => 'l j.',
		'day' => 'j.',
		'date' => 'j. F Y',
		'date-short' => 'j. F',
		'time' => 'H:i',
	],


	'message' => [
		'email-sent' => 'The e-mail is sent! We answer as soon as we can :)',
		'cookies' => 'Cookies are used to analyze traffic, and when a member logs in.',
	],
	
	'error' => [
		'email_fail' => 'Failed to send email. Please check your input.',
		
		'not_empty' => 'Cannot be empty',
		'email' => 'Invalid email address',
		'email_domain' => 'Invalid email domain',
	],
];
