<div id="jp_player"></div>
<div id="jp_container" class="jp-audio no-select">
	<div class="jp-gui">
		<div class="jp-progress">
			<div class="jp-seek-bar">
				<div class="jp-play-bar"></div>
			</div>
		</div>
		<div class="jp-controls">
			<span class="jp-current-time"></span>
			 / 
			<span class="jp-duration"></span>
			<a href="javascript:void(0)" class="jp-play-pause">{{#svg}}play-pause{{/svg}}</a>
		</div>
	</div>
</div>
