<?php

return [
	'About the site' => 'Om nettstedet',
	'Calendar' => 'Kalender',
	'Picture of the choir' => 'Bilde av koret',
	'The choir' => 'Koret',
	'Choir' => 'Koret',
	'Contact' => 'Kontakt',
	'Icons' => 'Ikoner',
	'Members' => 'Medlemmer',
	'Music' => 'Musikk',
	'Source code' => 'Kildekode',
	'Web developer' => 'Webutvikler',
	'Welcome' => 'Velkommen',
	'Login' => 'Logg inn',
	'Listen' => 'Lytt',

	'Choir practice' => 'Korøvelse',
	'On-the-road' => 'Langtur',
	'Warmup' => 'Oppvarming',
	'Sermon' => 'Gudstjeneste',
	'Concert' => 'Konsert',
	'Participate' => 'Delta',

	'Where?' => 'Hvor?',

	'E-Mail' => 'Epost',
	'Mail' => 'Post',
	'Bank details' => 'Bankdetaljer',

	'Your email' => 'Din epost',
	'Your subject' => 'Ditt emne',
	'Your message' => 'Din melding',

	'Sunday' => 'Søndag',
	'Monday' => 'Mandag',
	'Tuesday' => 'Tirsdag',
	'Wednesday' => 'Onsdag',
	'Thursday' => 'Torsdag',
	'Friday' => 'Fredag',
	'Saturday' => 'Lørdag',

	'January' => 'Januar',
	'February' => 'Februar',
	'March' => 'Mars',
	'April' => 'April',
	'May' => 'Mai',
	'June' => 'Juni',
	'July' => 'Juli',
	'August' => 'August',
	'September' => 'September',
	'October' => 'Oktober',
	'November' => 'November',
	'December' => 'Desember',

	'conductor' => 'dirigent',
	'soprano' => 'sopran',
	'alto' => 'alt',
	'tenor' => 'tenor',
	'bass' => 'bass',
	'technician' => 'tekniker',


	// @see http://php.net/manual/en/function.date.php#refsect1-function.date-parameters
	'date' => [
		'month-name' => 'F Y',
		'day-name' => 'l',
		'day' => 'j.',
		'date' => 'j. F Y',
		'time' => ' H:i',
	],

	'message' => [
		'email-sent' => 'Eposten er sendt! Vi svarer så fort vi klarer :)',
	],

	'error' => [
		'not_empty' => 'Kan ikke være tomt',
		'email' => 'Ugylding epost',
		'email_domain' => 'Ugylding epostdomene',
	],
];
