<?php

return [
	'About the site' => 'Om nettstedet',
	'Members' => 'Medlemmer',
	'Music' => 'Musikk',
	'Calendar' => 'Kalender',
	'Choir' => 'Koret',
	'Contact' => 'Kontakt',
	'Icons' => 'Ikoner',
	'Source code' => 'Kildekode',
	'Web developer' => 'Webutvikler',
	'Welcome' => 'Velkommen',

	'director' => 'dirigent',
	'soprano' => 'sopran',
	'alto' => 'alt',
	'tenor' => 'tenor',
	'bass' => 'bass',
	'technician' => 'tekniker',

];
