<?php

return [
	'About the site' => 'Om nettstedet',
	'Calendar' => 'Kalender',
	'Picture of the choir' => 'Bilde av koret',
	'The choir' => 'Koret',
	'Contact' => 'Kontakt',
	'Icons' => 'Ikoner',
	'Members' => 'Medlemmer',
	'Music' => 'Musikk',
	'Source code' => 'Kildekode',
	'Web developer' => 'Webutvikler',
	'Welcome' => 'Velkommen',

	'E-Mail' => 'Epost',
	'Mail' => 'Post',
	'Bank details' => 'Bankdetaljer',

	'Your email' => 'Din epost',
	'Your subject' => 'Ditt emne',
	'Your message' => 'Din melding',

	'conductor' => 'dirigent',
	'soprano' => 'sopran',
	'alto' => 'alt',
	'tenor' => 'tenor',
	'bass' => 'bass',
	'technician' => 'tekniker',

	'message' => [
		'email-sent' => 'Eposten er sendt! Vi svarer så fort vi klarer :)',
	],

	'error' => [
		'not_empty' => 'Kan ikke være tomt',
		'email' => 'Ugylding epost',
		'email_domain' => 'Ugylding epostdomene',
	],
];
