<?php
// TODO: Move to INI and cache upon read.
return [

	'Add to cart' => 'Legg i handlekurv',

	'Choir practice' => 'Korøvelse',
	'On-the-road' => 'Langtur',
	'Warmup' => 'Oppvarming',
	'Sermon' => 'Gudstjeneste',
	'Concert' => 'Konsert',
	'Choir trip' => 'Kortur',
	'Participating' => 'Deltar',

	'More information' => 'Mer informasjon',
	'Sheet music' => 'Notehefte',
	'Show PayPal cart' => 'Vis PayPal handlekurv',
	'Thank you!' => 'Takk!',

	'Come see us live!' => 'Kom se oss live!',
	'Subscribe to calendar' => 'Abonnér på kalender',
	'Get our latest albums!' => 'Skaff våre siste album!',
	'Follow us on Facebook!' => 'Følg oss på Facebook!',

	'Where?' => 'Hvor?',

	'Released' => 'Utgitt',
	'Total time' => 'Totaltid',

	'Your email' => 'Din epost',
	'Your subject' => 'Ditt emne',
	'Your message' => 'Din melding',
	'Your password' => 'Ditt passord',

	'Sunday' => 'Søndag',
	'Monday' => 'Mandag',
	'Tuesday' => 'Tirsdag',
	'Wednesday' => 'Onsdag',
	'Thursday' => 'Torsdag',
	'Friday' => 'Fredag',
	'Saturday' => 'Lørdag',

	'January' => 'Januar',
	'February' => 'Februar',
	'March' => 'Mars',
	'April' => 'April',
	'May' => 'Mai',
	'June' => 'Juni',
	'July' => 'Juli',
	'August' => 'August',
	'September' => 'September',
	'October' => 'Oktober',
	'November' => 'November',
	'December' => 'Desember',

	'Conductor' => 'Dirigent',
	'Soprano' => 'Sopran',
	'Alto' => 'Alt',
	'Tenor' => 'Tenor',
	'Bass' => 'Bass',
	'Technician' => 'Tekniker',

	'link' => [
		'need_password' => 'Trenger du passord?',
	],

	'title' => [
		'Home' => 'Forsiden',
		'Music' => 'Musikk',
		'Album' => 'Album',
		'Track' => 'Sang',
		'About the site' => 'Om nettstedet',
		'Calendar' => 'Kalender',
		'Choir' => 'Koret',
		'The choir' => 'Koret',
		'The cover' => 'Omslaget',
		'The songs' => 'Sangene',
		'Contact' => 'Kontakt',
		'Me' => 'Meg',
		'Members' => 'Medlemmer',
		'Everyone' => 'Alle',
		'Practice' => 'Øving',
		'Send message' => 'Send melding',
		'Songs' => 'Sanger',
		'Tools' => 'Verktøy',
		'Webshop' => 'Nettbutikk',
		'Welcome' => 'Velkommen',
		'Video' => 'Video',
		
		'Social' => 'Social',
		'E-Mail' => 'Epost',
		'Mail' => 'Post',
		'Bank details' => 'Bankdetaljer',
		
		'Login' => 'Logg inn',
		'Logout' => 'Logg ut',
		'Reset' => 'Jeg trenger passord…',

		'Cookies' => 'Cookies',
		'Icons' => 'Ikoner',
		'Source code' => 'Kildekode',
		'Web developer' => 'Webutvikler',
		'Web analytics' => 'Statistikk',
		'Graphics used for design' => 'Grafikk brukt til design',
	],
];
