<?php

return (object) [
	'global' => [
		'//cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js',
		'//cdnjs.cloudflare.com/ajax/libs/jquery/2.2.0/jquery.min.js',
		'//cdnjs.cloudflare.com/ajax/libs/nprogress/0.2.0/nprogress.min.js',
		'//cdnjs.cloudflare.com/ajax/libs/jplayer/2.9.2/jplayer/jquery.jplayer.min.js',
		'_/script.js',
		],

	'path' => [
		'/_/script.js' => [
			'src/_js/global.js',
			'src/_js/navigation.js',
			'src/_js/music.js',
			],
		],
];
