<?php

return (object) [
	'global' => [
		['media' => 'all',		'href' => '//cdnjs.cloudflare.com/ajax/libs/normalize/3.0.3/normalize.min.css'],
		['media' => 'all',		'href' => '//fonts.googleapis.com/css?family=Tangerine:700|Open+Sans:400,400italic|Open+Sans+Condensed:300'],
		['media' => 'screen',	'href' => '//cdnjs.cloudflare.com/ajax/libs/nprogress/0.2.0/nprogress.min.css'],
		['media' => 'all',		'href' => '_/style.css'],
		],

	'path' => [
		'/_/style.css' => 'src/_less/style.less',
	],
];
