<?php

return [

	'Add to cart' => 'Legg i handlekurv',

	'Choir practice' => 'Korøvelse',
	'On-the-road' => 'Langtur',
	'Warmup' => 'Oppvarming',
	'Sermon' => 'Gudstjeneste',
	'Concert' => 'Konsert',
	'Participating' => 'Deltar',

	'More information' => 'Mer informasjon',
	'Sheet music' => 'Notehefte',
	'Show PayPal cart' => 'Vis PayPal handlekurv',
	'Thank you!' => 'Takk!',

	'Come see us live!' => 'Kom og se oss live!',

	'Where?' => 'Hvor?',

	'E-Mail' => 'Epost',
	'Mail' => 'Post',
	'Bank details' => 'Bankdetaljer',

	'Your email' => 'Din epost',
	'Your subject' => 'Ditt emne',
	'Your message' => 'Din melding',
	'Your password' => 'Ditt passord',

	'Sunday' => 'Søndag',
	'Monday' => 'Mandag',
	'Tuesday' => 'Tirsdag',
	'Wednesday' => 'Onsdag',
	'Thursday' => 'Torsdag',
	'Friday' => 'Fredag',
	'Saturday' => 'Lørdag',

	'January' => 'Januar',
	'February' => 'Februar',
	'March' => 'Mars',
	'April' => 'April',
	'May' => 'Mai',
	'June' => 'Juni',
	'July' => 'Juli',
	'August' => 'August',
	'September' => 'September',
	'October' => 'Oktober',
	'November' => 'November',
	'December' => 'Desember',

	'Conductor' => 'Dirigent',
	'Soprano' => 'Sopran',
	'Alto' => 'Alt',
	'Tenor' => 'Tenor',
	'Bass' => 'Bass',
	'Technician' => 'Tekniker',

	'link' => [
		'need_password' => 'Trenger du passord?',
	],

	'title' => [
		'Home' => 'Forsiden',
		'Music' => 'Musikk',
		'About the site' => 'Om nettstedet',
		'Calendar' => 'Kalender',
		'Choir' => 'Koret',
		'Contact' => 'Kontakt',
		'Me' => 'Meg',
		'Member area' => 'Medlemsområde',
		'Members' => 'Medlemmer',
		'Everyone' => 'Alle',
		'Practice' => 'Øving',
		'Songs' => 'Sanger',
		'Webshop' => 'Nettbutikk',
		'Welcome' => 'Velkommen',
		'Video' => 'Video',
		
		'Login' => 'Logg inn',
		'Logout' => 'Logg ut',

		'Cookies' => 'Cookies',
		'Icons' => 'Ikoner',
		'Source code' => 'Kildekode',
		'Web developer' => 'Webutvikler',
		'Web analytics' => 'Statistikk',
		'Graphics used for design' => 'Grafikk brukt til design',
		'Subscribe to calendar' => 'Abonnér på kalender',
		'Get our latest albums!' => 'Skaff våre siste album!',
	],

	'message' => [
		'email-sent' => 'Eposten er sendt! Vi svarer så fort vi klarer :)',
		'cookies' => 'Cookies brukes for å analysere trafikk, og når meldlemmer logger inn.',
	],

	'error' => [
		'invalid_login' => 'Ugyldig login',
		'email_fail' => 'Kunne ikke sende eposten. Sjekk at du at du har fyllt ut skjemaet riktig.',

		'not_empty' => 'Kan ikke være tomt',
		'email' => 'Ugylding epost',
		'email_domain' => 'Ugylding epostdomene',
	],
];
